//! Generated gRPC types + small auth helpers.
//!
//! Both the discord bot (`tomo-discord`) and the admin web service
//! (`tomo-admin`) depend on this crate. The bot implements the server
//! trait; the admin uses the generated client.

pub mod auth;

/// Generated by tonic-build from `proto/tomo.proto`.
pub mod proto {
    tonic::include_proto!("tomo.v1");
}

pub use proto::*;
pub use proto::tomo_control_client::TomoControlClient;
pub use proto::tomo_control_server::{TomoControl, TomoControlServer};
