[package]
name = "tomo-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tomo-core = { workspace = true }
tomo-rpc  = { workspace = true }

# Web
axum       = { workspace = true }
axum-extra = { workspace = true }
tower      = { workspace = true }
tower-http = { workspace = true }
tonic      = { workspace = true }

# OAuth
oauth2  = { workspace = true }
reqwest = { workspace = true }

# Async / util
async-trait = { workspace = true }
chrono      = { workspace = true }
flume       = { workspace = true }
http        = "1"
sha2        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
time        = "0.3"
tokio       = { workspace = true }
tracing     = { workspace = true }
url         = { workspace = true }
