[package]
name = "tomo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait    = { workspace = true }
dotenvy        = { workspace = true }
serde          = { workspace = true }
thiserror      = { workspace = true }
tokio          = { workspace = true }
tracing        = { workspace = true }
twilight-model = { workspace = true }
